// Modified by Richard Austin in 2026
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    id("jacoco")
    id("java-gradle-plugin")
    id("com.gradle.plugin-publish") version "2.1.1"
    id("org.jetbrains.kotlin.jvm") version ("2.4.20-Beta1")
}

version = "0.0.1"
group = "io.github.richard-austin"

repositories {
    mavenLocal()
    mavenCentral()
}

kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.13.4"))
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("org.junit.jupiter:junit-jupiter")
}

tasks.test {
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    reports {
        html.required = true
    }
}

gradlePlugin {
    website = "https://github.com/richard-austin/tinygo-plugin"
    vcsUrl = "https://github.com/richard-austin/tinygo-plugin.git"
    plugins {
        create("tinygo-plugin") {
            id = "io.github.richard-austin.tinygo-plugin"
            displayName = "TinyGo Gradle plugin"
            implementationClass = "io.github.richard_austin.TinyGoPlugin"
            tags = listOf("go", "golang")
            description = "This is derived from https://github.com/dm0275/go-plugin to make a new plugin for projects using tinygo."
         }
    }
}
