// Modified by Richard Austin in 2026
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 */

plugins {
    id("jacoco")
    id("java-gradle-plugin")
    id("com.gradle.plugin-publish") version "2.1.1"
    id("org.jetbrains.kotlin.jvm") version ("2.4.20-Beta1")
}

version = "0.7.1"
group = "io.github.richard-austin"

repositories {
    mavenLocal()
    mavenCentral()
}

kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.13.4"))
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("org.junit.jupiter:junit-jupiter")
}

tasks.test {
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    reports {
        html.required = true
    }
}

gradlePlugin {
    website = "https://github.com/richard-austin/go-plugin"
    vcsUrl = "https://github.com/richard-austin/go-plugin.git"
    plugins {
        create("go-plugin") {
            id = "io.github.richard-austin.go-plugin"
            displayName = "Go Gradle plugin"
            implementationClass = "io.github.richard_austin.GoPlugin"
            tags = listOf("go", "golang")
            description = "This is a fork of https://github.com/dm0275/go-plugin modified to provide compatibility with gradle 10."
                    "The `Go-Plugin` is a Gradle plugin for Go projects. This plugin does not intend to replace" +
                    " Go's native dependency management system, instead this plugin focuses on replacing traditional " +
                    "task orchestrators like Make, offering a more versatile and reusable approach for task automation."
        }
    }
}
